title: <p align="center"> Gautam Singh</p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/gautam-singh/">LinkedIn</a> |
  <a href="https://github.com/gautamsbh">GitHub</a>
  
  <br>
  <br>
  </p>



theme: jekyll-theme-minimal
